/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthManagerRouteImport } from './routes/_auth.manager'
import { Route as AuthEmployeeRouteImport } from './routes/_auth.employee'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthManagerIndexRouteImport } from './routes/_auth.manager.index'
import { Route as AuthEmployeeIndexRouteImport } from './routes/_auth.employee.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthManagerRoute = AuthManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeRoute = AuthEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerIndexRoute = AuthManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthManagerRoute,
} as any)
const AuthEmployeeIndexRoute = AuthEmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEmployeeRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/employee': typeof AuthEmployeeRouteWithChildren
  '/manager': typeof AuthManagerRouteWithChildren
  '/admin/': typeof AuthAdminIndexRoute
  '/employee/': typeof AuthEmployeeIndexRoute
  '/manager/': typeof AuthManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminIndexRoute
  '/employee': typeof AuthEmployeeIndexRoute
  '/manager': typeof AuthManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/employee': typeof AuthEmployeeRouteWithChildren
  '/_auth/manager': typeof AuthManagerRouteWithChildren
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/employee/': typeof AuthEmployeeIndexRoute
  '/_auth/manager/': typeof AuthManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/'
    | '/employee/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin' | '/employee' | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/employee'
    | '/_auth/manager'
    | '/_auth/admin/'
    | '/_auth/employee/'
    | '/_auth/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/manager': {
      id: '/_auth/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthManagerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee': {
      id: '/_auth/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthEmployeeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manager/': {
      id: '/_auth/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthManagerIndexRouteImport
      parentRoute: typeof AuthManagerRoute
    }
    '/_auth/employee/': {
      id: '/_auth/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof AuthEmployeeIndexRouteImport
      parentRoute: typeof AuthEmployeeRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthEmployeeRouteChildren {
  AuthEmployeeIndexRoute: typeof AuthEmployeeIndexRoute
}

const AuthEmployeeRouteChildren: AuthEmployeeRouteChildren = {
  AuthEmployeeIndexRoute: AuthEmployeeIndexRoute,
}

const AuthEmployeeRouteWithChildren = AuthEmployeeRoute._addFileChildren(
  AuthEmployeeRouteChildren,
)

interface AuthManagerRouteChildren {
  AuthManagerIndexRoute: typeof AuthManagerIndexRoute
}

const AuthManagerRouteChildren: AuthManagerRouteChildren = {
  AuthManagerIndexRoute: AuthManagerIndexRoute,
}

const AuthManagerRouteWithChildren = AuthManagerRoute._addFileChildren(
  AuthManagerRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthEmployeeRoute: typeof AuthEmployeeRouteWithChildren
  AuthManagerRoute: typeof AuthManagerRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthEmployeeRoute: AuthEmployeeRouteWithChildren,
  AuthManagerRoute: AuthManagerRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
